#cargo-features = ["edition2024"]

[package]
name = "fe-o-godot-macros"
version = "0.0.1"
edition = "2021"

[lib]
#proc-macro = true

[dependencies]
godot           = { git = "https://github.com/rustlang-issue-14740/gdext", branch = "master" }